from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
  path('index/', views.index, name='index'),
  path('login/', views.login, name='login'),
  path('add/', views.add, name='add'),
  path('principal/', views.principal, name='principal'),
  path('principal/viewstudent/', views.viewstudent, name='viewstudent'),
  path('principal/viewadmin/', views.viewadmin, name='viewadmin'),
  path('principal/viewstaff/', views.viewstaff, name='viewstaff'),
  path('principal/addadminn/', views.addadminn, name='addadminn'),
  path('principal/addadminn/addadmin/', views.addadmin, name='addadmin'),
  path('principal/addstafff/', views.addstafff, name='addstafff'),
  path('principal/addstafff/addstaff/', views.addstaff, name='addstaff'),
  path('principal/add/', views.add, name='add'),
  path('principal/add/addrecord/', views.addrecord, name='addrecord'),
  path('login/loginrecord/', views.loginrecord, name='loginrecord'),
  path('login/loginrecord/addrecord/', views.addrecord, name='addrecord'),
  path('login/loginrecord/viewadmin/', views.viewadmin, name='viewadmin'),
  path('login/loginrecord/viewstudent/', views.viewstudent, name='viewstudent'),
  path('login/loginrecord/viewstaff/', views.viewstaff, name='viewstaff'),
  path('login/loginrecord/addadminn/', views.addadminn, name='addadminn'),
  path('login/loginrecord/addadminn/addadmin/', views.addadmin, name='addadmin'),
  path('login/loginrecord/addstafff/', views.addstafff, name='addstafff'),
  path('login/loginrecord/addstafff/addstaff/', views.addstaff, name='addstaff'),
  path('login/loginrecord/add/', views.add, name='add'),
  path('login/loginrecord/add/addrecord/', views.addrecord, name='addrecord'),
  path('add/addrecord/', views.addrecord, name='addrecord'),
  path('index/addcircular/', views.addcircular, name='addcircular'),
  path('login/loginrecord/addcircular/', views.addcircular, name='addcircular'),
  path('index/addcircular/addrecordcircular/', views.addrecordcircular, name='addrecordcircular'),
  path('login/loginrecord/addcircular/addrecordcircular/', views.addrecordcircular, name='addrecordcircular'),
  path('studentlogin/', views.studentlogin, name='studentlogin'),
  path('studentlogin/studentloginrecord/', views.studentloginrecord, name='studentloginrecord'),
  path('principal/change/', views.change, name='change'),
  path('principal/change/changedesign/', views.changedesign, name='changedesign'),
  path('principal/change/changedesign/changing/', views.changing, name='changing'),
  path('principal/delete/', views.delete, name='delete'),
  path('principal/delete/deletex/', views.deletex, name='deletex'),
  path('login/loginrecord/change/', views.change, name='change'),
  path('login/loginrecord/change/changedesign/', views.changedesign, name='changedesign'),
  path('login/loginrecord/change/changedesign/changing/', views.changing, name='changing'),
  path('login/loginrecord/delete/', views.delete, name='delete'),
  path('login/loginrecord/delete/deletex/', views.deletex, name='deletex'),
  path('stafflogin/', views.stafflogin, name='stafflogin'),
  path('stafflogin/staffloginn/', views.staffloginn, name='staffloginn'),
  path('principal/allocate/', views.allocate, name='allocate'),
  path('login/loginrecord/allocate/allocatee/', views.allocatee, name='allocatee'),
  path('login/loginrecord/allocate/', views.allocate, name='allocate'),
  path('login/loginrecord/allocate/allocatee/', views.allocatee, name='allocatee'),
  path('studentlogin/studentloginrecord/assign/', views.assign, name='assign'),
  path('studentlogin/studentloginrecord/assign/assignment/', views.assignment, name='assignment'),
  path('principal/viewstudent/addcircular/', views.addcircular, name='addcircular'),
  path('principal/viewstudent/addcircular/addrecordcircular/', views.addrecordcircular, name='addrecordcircular'),
  path('principal/uploadstd/', views.upload_imagestd, name='uploadstd'),
  path('login/loginrecord/viewstudent/addcircular/', views.addcircular, name='addcircular'),
  path('login/loginrecord/viewstudent/addcircular/addrecordcircular/', views.addrecordcircular, name='addrecordcircular'),
  path('login/loginrecord/uploadstd/', views.upload_imagestd, name='uploadstd'),
  path('successstd/', views.successstd, name='successstd'),
  path('login/loginrecord/uploadstd/gallerystd/', views.view_imagesstd, name='gallerystd'),
  path('principal/uploadx/', views.upload_imagex, name='uploadx'),
  path('login/loginrecord/uploadx/', views.upload_imagex, name='uploadx'),
  path('successx/', views.successx, name='successx'),
  path('login/loginrecord/uploadx/galleryx/', views.view_imagesx, name='galleryx'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
