# Generated by Django 5.2.8 on 2025-12-12 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ids', models.CharField(max_length=100)),
                ('age', models.CharField(max_length=100)),
                ('classs', models.CharField(max_length=100)),
                ('fee', models.CharField(max_length=100)),
                ('balance', models.CharField(max_length=100)),
                ('percent', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Adminn',
        ),
    ]
