# Generated by Django 5.2.8 on 2025-12-13 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_circular'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('password', models.CharField(max_length=1000)),
                ('designation', models.CharField(max_length=1000)),
            ],
        ),
    ]
