# Generated by Django 5.2.8 on 2025-12-15 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addmi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('password', models.CharField(max_length=1000)),
                ('designation', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('password', models.CharField(max_length=1000)),
                ('designation', models.CharField(max_length=1000)),
            ],
        ),
    ]
