# Generated by Django 5.2.8 on 2025-12-15 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_addmi_staff'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Addmi',
            new_name='Addmmi',
        ),
        migrations.RenameModel(
            old_name='Staff',
            new_name='Staffss',
        ),
    ]
