# Generated by Django 5.2.8 on 2025-12-15 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_rename_addmi_addmmi_rename_staff_staffss'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addmmi',
            old_name='designation',
            new_name='college',
        ),
        migrations.RenameField(
            model_name='staffss',
            old_name='designation',
            new_name='college',
        ),
        migrations.RenameField(
            model_name='staffss',
            old_name='password',
            new_name='dept',
        ),
    ]
