# Generated by Django 5.2.8 on 2025-12-15 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_rename_designation_addmmi_college_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Addmmi',
        ),
        migrations.DeleteModel(
            name='Staffss',
        ),
    ]
