# Generated by Django 5.2.8 on 2025-12-18 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_delete_addmmi_delete_staffss'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staffname', models.CharField(max_length=1000)),
                ('stdid1', models.CharField(max_length=1000)),
                ('stdid2', models.CharField(max_length=1000)),
            ],
        ),
    ]
