# Generated by Django 5.2.8 on 2025-12-19 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0010_assignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignmentx',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment', models.CharField(max_length=1000)),
                ('name', models.CharField(max_length=1000)),
            ],
        ),
        migrations.DeleteModel(
            name='Assignment',
        ),
    ]
