# Generated by Django 5.2.8 on 2025-12-29 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0012_imageupload'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('clas', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='uploads/')),
                ('marksheet', models.ImageField(upload_to='uploads/')),
            ],
        ),
    ]
